name: my-project
provider: docker
extends:
  - inizio/vendetta-config-inizio
plugins:
  - golang
  - node
services:
  web:
    port: 3000
docker:
  image: ubuntu:22.04
  dind: true
hooks:
  setup: .vendetta/hooks/up.sh
